// Mocks generated by Mockito 5.4.0 from annotations
// in FMoments/test/cubit/moments_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:FMoments/model/user_info_data.dart' as _i2;
import 'package:FMoments/repository/moments_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network/model/tweet_resp.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserInfo_0 extends _i1.SmartFake implements _i2.UserInfo {
  _FakeUserInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MomentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMomentsRepository extends _i1.Mock implements _i3.MomentsRepository {
  MockMomentsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserInfo> fetchUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.UserInfo>.value(_FakeUserInfo_0(
          this,
          Invocation.method(
            #fetchUserInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserInfo>);
  @override
  _i4.Future<List<_i5.Tweet>> fetchTweets() => (super.noSuchMethod(
        Invocation.method(
          #fetchTweets,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Tweet>>.value(<_i5.Tweet>[]),
      ) as _i4.Future<List<_i5.Tweet>>);
}
